jobs:
  refresh-ebay-token:
    name: "🔄 Refresh eBay OAuth Token"
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install Dependencies
        run: pip install requests

      - name: 🔍 환경 변수 확인 (디버깅)
        run: |
          echo "🔍 EBAY_CLIENT_ID=${{ secrets.EBAY_CLIENT_ID }}"
          echo "🔍 EBAY_CLIENT_SECRET=${{ secrets.EBAY_CLIENT_SECRET }}"
          echo "🔍 EBAY_REFRESH_TOKEN=${{ secrets.EBAY_REFRESH_TOKEN }}"

      - name: 🔄 eBay OAuth 토큰 갱신
        run: python get_ebay_oauth_token.py
